CFLAGS=-Wall -Wextra -pedantic -g

all: recursive_binary_search iterative_binary_search
clean:
	rm -rf recursive_binary_search recursive_binary_search.dSYM/
	rm -rf iterative_binary_search iterative_binary_search.dSYM/
