CC=cc
CFLAGS=-Wall -Wextra -pedantic -g

main:
	$(CC) $(CFLAGS) circular_buffer.c -o circular_buffer
tests:
	$(CC) $(CFLAGS) circular_buffer.c Testcircular_buffer.c ../test-framework/Unity/src/unity.c -o Testcircular_buffer